global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'whalli-monitor'

scrape_configs:
  - job_name: 'whalli-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
