#!/bin/bash

# ========================================
# GUIDE RAPIDE - Configuration Secrets GitHub
# ========================================

echo "╔════════════════════════════════════════════════╗"
echo "║  Whalli - Configuration Secrets GitHub        ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "✅ 18/21 secrets déjà configurés (86%)"
echo "⏳ 3 secrets serveur restants (14%)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 SECRETS MANQUANTS :"
echo ""
echo "   1. SSH_PRIVATE_KEY  - Clé SSH pour déploiement"
echo "   2. SERVER_HOST      - IP du serveur (ex: 123.45.67.89)"
echo "   3. SERVER_USER      - Username SSH (ex: ubuntu)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 OPTION 1 : Configuration Automatique (Recommandé)"
echo ""
echo "   $ ./scripts/add-server-secrets.sh"
echo ""
echo "   • Guide interactif étape par étape"
echo "   • Génération automatique de clé SSH"
echo "   • Configuration complète en 2 minutes"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🛠️  OPTION 2 : Configuration Manuelle"
echo ""
echo "   # 1. Générer clé SSH"
echo "   $ ssh-keygen -t ed25519 -C \"github-actions\" -f ~/.ssh/github_deploy_whalli"
echo ""
echo "   # 2. Copier clé sur serveur"
echo "   $ ssh-copy-id -i ~/.ssh/github_deploy_whalli.pub USER@SERVER_IP"
echo ""
echo "   # 3. Ajouter secrets à GitHub"
echo "   $ echo \"SERVER_IP\" | gh secret set SERVER_HOST --repo Whalli/whalli"
echo "   $ echo \"USER\" | gh secret set SERVER_USER --repo Whalli/whalli"
echo "   $ cat ~/.ssh/github_deploy_whalli | gh secret set SSH_PRIVATE_KEY --repo Whalli/whalli"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 VÉRIFICATION"
echo ""
echo "   # Liste des secrets"
echo "   $ gh secret list --repo Whalli/whalli"
echo ""
echo "   # Interface web"
echo "   https://github.com/Whalli/whalli/settings/secrets/actions"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTATION"
echo ""
echo "   • scripts/README.md              - Guide complet des scripts"
echo "   • GITHUB_SECRETS_STATUS.md       - État détaillé (18/21)"
echo "   • GITHUB_SECRETS_VISUAL_GUIDE.md - Diagrammes et flux"
echo "   • GITHUB_SECRETS_SUMMARY.md      - Résumé en français"
echo "   • GITHUB_SECRETS_CHECKLIST.md    - Checklist interactive"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 CONSEIL : Utilisez Option 1 pour une configuration rapide et guidée !"
echo ""
